<Project>
  <PropertyGroup>
    <!-- Enable central package management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!--....Back end-->
    <PackageVersion Include="MessagePack" Version="3.1.4" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <!--....Maui Mob-Desk-->
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageVersion Include="ReactiveUI" Version="21.0.1" />
    <PackageVersion Include="ReactiveUI.Maui" Version="22.0.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.4" />
    <PackageVersion Include="CommunityToolkit.HighPerformance" Version="8.4.0" />
    <PackageVersion Include="CommunityToolkit.Maui" Version="12.2.0" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="9.0.110" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.110" />
    <PackageVersion Include="Microsoft.VisualStudio.Utilities" Version="17.14.40264" />
    <PackageVersion Include="System.Security.Cryptography.Cng" Version="5.0.0" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="9.0.9" />
    <PackageVersion Include="Telerik.UI.for.Maui" Version="11.0.0" />
    <!--....Maui hybrid Web-->
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="9.0.7" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.7" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.7" PrivateAssets="all" />
  </ItemGroup>
</Project>