<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable> 
		<RootNamespace>Resume.Maui.Shared</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.HighPerformance"  />
		<PackageReference Include="CommunityToolkit.Maui" />
		<PackageReference Include="CommunityToolkit.Mvvm"  />
		<PackageReference Include="Microsoft.Maui.Controls" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" />
		<PackageReference Include="Microsoft.VisualStudio.Utilities" />
		<PackageReference Include="Telerik.UI.for.Maui" />
		
	</ItemGroup> 
	<ItemGroup>
	  <MauiXaml Update="Controls\SignaturePad.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\TextInput.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup> 
	<ItemGroup>
	  <Folder Include="Services\Interfaces\" />
	</ItemGroup>

</Project>
