<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-ios</TargetFramework>
		<SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
		<OutputType>Exe</OutputType>
		<RootNamespace>Resume.Maui.iOS</RootNamespace>
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseMaui>true</UseMaui>
		<AssemblyName>Resume.Maui.iOS</AssemblyName>
		<AssemblyTitle>Resume.Maui.iOS</AssemblyTitle>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Resume.Maui\Resume.Maui.csproj" />
	</ItemGroup>

</Project>
